filter:
  paths:
    - 'src/*'
  excluded_paths:
    - 'tests/*'

tools:
  php_code_coverage:
    test_command: vendor/bin/phpunit

checks:
  php: true

coding_style:
  php:
    indentation:
      general:
        size: 1

build:
  environment:
    variables:
      CC_TEST_REPORTER_ID: da3d1c18a95c20bc1b1a996dfa9cfb7d4de1d9e67acc8d340c25b53c9a528de3
    php:
      version: 7.1
  nodes:
    analysis:
      project_setup:
        override:
          - 'true'
      tests:
        override:
          - php-scrutinizer-run
    tests: true
  cache:
    disabled: false
    directories:
      - vendor/
  tests:
    override:
      - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
      - chmod +x ./cc-test-reporter
      - ./cc-test-reporter before-build
      -
        command: 'vendor/bin/phpunit --coverage-clover clover.xml'
        coverage:
          file: 'clover.xml'
          format: 'clover'
      - ./cc-test-reporter after-build --coverage-input-type clover --exit-code $?