site_name: Perú Consultas
site_url: https://giansalex.github.io/peru-consult
site_description: 'Documentación de Perú Consultas, DNI - Reniec, RUC - Sunat '
site_author: 'Giancarlos Salas'

# Repository
repo_name: 'giansalex/peru-consult'
repo_url: 'https://github.com/giansalex/peru-consult'

pages:
    - Principal: index.md
    - Dni: dni.md
    - Ruc: ruc.md

# Configuration
theme:
  name: 'material'
  favicon: 'img/peru.png'
  logo: 'img/peru.png'
  language: 'es'
  palette:
    primary: 'Teal'
    accent: 'Indigo'

extra_css:
  - 'css/prism.css'
extra_javascript:
  - 'js/prism.js'

extra:
  social:
    - type: 'github'
      link: 'https://github.com/giansalex'
  author:
    github: giansalex

# Google Analytics
google_analytics:
  - 'UA-90097417-4'
  - 'auto'

# Extensions
markdown_extensions:
  - admonition
  - codehilite:
      css_class: code
      use_pygments: false
      guess_lang: false
  - toc:
      permalink: true
