version: 2
jobs:
  build:
    docker:
      - image: circleci/php:7.1
    steps:
      - checkout
      - run: sudo apt install -y git libfreetype6-dev libjpeg62-turbo-dev
      - run: sudo docker-php-ext-configure gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/
      - run: sudo docker-php-ext-install -j$(nproc) gd
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "composer.json" }}
          - v1-dependencies-
      - run: composer install -n --prefer-dist
      - save_cache:
          paths:
            - ./vendor
          key: v1-dependencies-{{ checksum "composer.json" }}
      - run: mkdir -p test-results/behat
      - run: ./vendor/bin/phpunit
      - run: ./vendor/bin/behat --config behat.yml --tags "~@deprecated" -f pretty -o std -f junit -o test-results/behat/
      - store_test_results:
          path: test-results
  deploy:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          name: Deploy Docs
          command: |
            python3 -m venv venv
            . venv/bin/activate
            chmod +x .circleci/deploy.sh
            ./.circleci/deploy.sh
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "venv"
workflows:
  version: 2
  build_test_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
