version: 2
jobs:
  build:
    branches:
      ignore:
        - gh-pages
    docker:
      - image: circleci/php:7.1-node-browsers
    steps:
      - checkout
      - run: sudo composer self-update
      - run: composer install --prefer-source --no-interaction --dev
      - run: ./vendor/bin/phpunit --configuration phpunit.xml
      - run: ./vendor/bin/behat --config behat.yml

workflows:
  version: 2
  build_and_test:
    jobs:
      - build

