name: CI

on: [push, pull_request]

jobs:
  test:
    name: PHP Tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: Setup PHP
      uses: shivammathur/setup-php@1.1.1
      with:
        php-version: 7.1
    - run: composer install
    - name: Install Coveralls
      run: composer require php-coveralls/php-coveralls;
    - name: Create test directory
      run: mkdir -p test-results/behat
    - run: vendor/bin/phpunit
      env:
        MOCK_URL: ${{ secrets.MockServer }}
    - run: vendor/bin/behat --config behat.yml -f pretty -o std -f junit -o test-results/behat/
    - name: Report code coverage
      run: vendor/bin/php-coveralls -v
