name: CI

on: [push, pull_request]

jobs:
  test:
    name: PHP Tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: Setup PHP
      uses: shivammathur/setup-php@1.1.1
      with:
        php-version: 7.1
    - run: composer install
    - name: Install Coveralls
      run: composer require php-coveralls/php-coveralls;
    - name: Create test directory
      run: mkdir -p test-results/behat
    - name: PHPUnit Tests
      run: vendor/bin/phpunit
      env:
        MOCK_URL: ${{ secrets.MockServer }}
    - name: BDD Tests
      run: vendor/bin/behat --config behat.yml -f pretty -o std -f junit -o test-results/behat/
    - name: Create branch for coveralls
      run: git checkout -b ${GIT_REMOTE_BRANCH:11}
      env:
        GIT_REMOTE_BRANCH: ${{ github.ref }}
    - name: Report code coverage
      run: vendor/bin/php-coveralls && echo "Current branch $CI_BRANCH"
      env:
        CI_NAME: Github Actions
        CI_BRANCH: ${GITHUB_REF}
        CI_PULL_REQUEST: $([ "${GITHUB_EVENT_NAME}" == "pull_request" ] && echo "true" || echo "false")
        COVERALLS_REPO_TOKEN: ${{ secrets.coverallsToken }}
